### PR TITLE
Adds an example unit test that reads some information from an external resource file

### PR DESCRIPTION
**Pull request by filmil**
Try it out by issuing:

``` bash
bazel test //lib/...
```

Resource file access is the current difference between a bazel-built
golang source code and test built with 'go test'.

If you wanted to access the file when testing with 'go test', you would
have to open as:

``` go
file, err := os.Open("file.txt)
```

With bazel it will have to be:

``` go
file, err := os.Open("lib/file.txt)
```

### CODE REVIEW

**Comment by achew22** [comment]
Filip,

Thanks so much for your contribution! I'd like to see if there is any activity on the bazel-dev thread (https://groups.google.com/forum/#!topic/bazel-dev/1NteKkXgsoE) before merging this. Who knows, maybe there is a better way to do this. I'm definitely not an expert in Golang or Bazel so I'm going to let the experts weigh in before I merge this.

If there is no action by December 5th, I will merge this. Does that work for you?

**Comment by filmil** [comment]
OK

**Comment by achew22** [comment]
Hey, I am definitely late on this (sorry, I went on vacation).

Based on recent events, would you still like this merged?

**Comment by filmil** [comment]
Yes, and then we should probably correct it to pass with latest bazel.
This is because the current docs don't explain quite well how to set tests
up (there's more loading to do etc, so a live example goes a long way to
show how it's done).

If you don't feel like fixing that up, I'll make a new pull request as soon
as I have the time to do so.

There is a serious limitation to bazel's handling of golang: it requires
you to write a BUILD file per each external dependency, which is  a drag.

F

**Comment by achew22** [comment]
I couldn't agree with you more that having a working example goes a long long way to being able to get started.

I'm going to guess you're referring to https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/qeeQEQCQlo8/A3DYgQlwCgAJ

When Bazel has the ability to create custom remotes I assume we will be able hook up a generic BUILD with a :go_default_library with srcs = glob(["*_/_.go"])  and slap that on the vast majority of the go libraries I want to use.

I'm going to be playing with a PR for gengo/grpc-gateway today so I probably won't get around to fixing up this PR. If you could get it to a place were it builds and then squash all the commits into a single one, I'll be happy to merge this in..

Thanks!

**Comment by achew22** [comment]
Done. I took your changes and squashed them into one commit (76744acf43fb54aef07685bcab78c409d1c5f741). Then I I updated Bazel to 99a89acf4c7608eb56d77cb746db32842833c6c1 and copied the go build_rules out of there and updated the test file to reflect that. If you could take a look at master and confirm that this is what you expected.

Thanks for helping! Soon this repo will be a really useful sample for anyone who wants to build Go using Bazel.

**Pull request closed without merging**
